name=ButtonGestures
version=3.0.0
author=Trent M. Wyatt
maintainer=Trent M. Wyatt <robotics@trentwyatt.com>
sentence=Use one button for up to 6 different non-blocking gesture functions!
paragraph=Using single, double, or triple press, long or short gestures you can have up to 6 different functions registered to be called without blocking the rest of your sketch.
category=Signal Input/Output
url=https://github.com/ripred/ButtonGestures
architectures=avr
includes=ButtonGestures.h
