name: Arduino-lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Arduino Lint
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh

      - name: Run Arduino Lint
        run: |
          set -euo pipefail
          ./bin/arduino-lint --compliance strict --library-manager update "$GITHUB_WORKSPACE"
